### ISSUE TITLE
Add new Airbnb error

### ISSUE THREAD

**Issue by VedanshSharma53** [Zohaib-Develper/Wanderlust#2]
![image](https://github.com/user-attachments/assets/ea942ed5-bdf3-4998-ba2f-1ffeb6255447)
shows this when i try to add new airbnb...
wht could be the issue??

**Comment by Zohaib-Develper** [comment]
For me, it is working alright. Could you please check again and then let me know whether the issue is resolved or not

**Comment by VedanshSharma53** [comment]
i am not using mapbox token
and the image that i give in add new form is going to my cloudinary folder 
but it's not adding to the database
any specific functions or methods that i should keep in mind??
@Zohaib-Develper

**Comment by Zohaib-Develper** [comment]
We cannot add images to Mongodb database. We can only save the url or path (which is obviously a string) of the image to database

**Comment by VedanshSharma53** [comment]
Not about the image
Nothing is storing in the db that I enter in the from 
@Zohaib-Develper

**Comment by Zohaib-Develper** [comment]
Then there might be some issue in connecting to db. Have you created  .env file? if you haven't , you should create .env file by following steps mentioned in the README.md file
